bucket_prefix = "devops-directive-web-app-data"
domain        = "devopsdeployed.com"
db_name       = "mydb"
db_user       = "foo"
cloudflare_api_token="QYXXvHtVgmQDSl7nn9nWNurGYjD-q37ukOHsdhOV"
# db_pass = "foobarbaz"
